stages:
  data:
    cmd: python data.py
    outs:
      - data/dataset.csv
  process:
    cmd: python process.py
    deps:
      - data/dataset.csv
      - process.py
    outs:
      - data/proc_dataset.csv